Update app config file

diff --git a/devops/azure_pipelines.yml b/devops/azure_pipelines.yml
--- a/devops/azure_pipelines.yml
+++ b/devops/azure_pipelines.yml
@@ -53,10 +53,6 @@ jobs:
 #        displayName: Run code formatting checks
 
       - bash: |
-          coverage run --source=src -m pytest tests/** --capture=no --show-capture=no --doctest-modules --junitxml=junit/test-results.xml
-        displayName: Run tests with coverage
-
-      - bash: |
           set -e
           echo "Build backstage backend..."
           aip app container build --container_name backstage_app_back
@@ -65,50 +61,56 @@ jobs:
         displayName: Build docker images
 
 
-#  - job: Doc
-#    displayName: Build and Push Documentation
-#    dependsOn: TestAndBuild
-#    pool:
-#      vmImage: ubuntu-latest
-#    container:
-#      image: aziecr1aip001.azurecr.io/aip_devcontainer
-#      endpoint: SDXSandbox_Docker_Registry
-#    steps:
-#      - script: |
-#          echo "Current branch is $(Build.SourceBranch)"
-#          if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
-#            VERSION='latest'
-#          elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
-#            VERSION='merge'
-#          else
-#            VERSION='tmp'
-#          fi
-#          PATHDOC=docs/build/html/
-#          echo "##vso[task.setvariable variable=VERSION]$VERSION"
-#          echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
-#          echo "Found VERSION=$VERSION"
-#          echo "Found PATHDOC=$PATHDOC"
-#        displayName: Get doc version
-#
-#      - script: |
-#          if [[ -d backstage ]]; then cd backstage ; fi
-#          aip core docs build --add_markdowns --install_packages
-#          if [[ ! -d $(PATHDOC) ]];
-#          then
-#            echo "Not found generated doc at path $(PATHDOC)"
-#            exit 1
-#          fi
-#        displayName: Build doc
-#
-#      - task: AzureCLI@2
-#        inputs:
-#          azureSubscription: $(serviceConnectionSandbox)
-#          scriptType: bash
-#          scriptLocation: inlineScript
-#          inlineScript: |
-#            if [[ -d backstage ]]; then cd backstage ; fi
-#            aip core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
-#        displayName: Push doc
+  - job: Doc
+    displayName: Build and Push Documentation
+    dependsOn: TestAndBuild
+    pool:
+      vmImage: ubuntu-latest
+    container:
+      image: aziecr1aip001.azurecr.io/aip_devcontainer
+      endpoint: SDXSandbox_Docker_Registry
+    steps:
+      - task: PipAuthenticate@1
+        inputs:
+          artifactFeeds: $(artifactFeeds)
+          onlyAddExtraIndex: true
+        displayName: Pip authentication
+
+      - script: |
+          echo "Current branch is $(Build.SourceBranch)"
+          if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
+            VERSION='latest'
+          elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
+            VERSION='merge'
+          else
+            VERSION='tmp'
+          fi
+          PATHDOC=docs/build/html/
+          echo "##vso[task.setvariable variable=VERSION]$VERSION"
+          echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
+          echo "Found VERSION=$VERSION"
+          echo "Found PATHDOC=$PATHDOC"
+        displayName: Get doc version
+
+      - script: |
+          if [[ -d backstage ]]; then cd backstage ; fi
+          aip core docs build --add_markdowns --install_packages
+          if [[ ! -d $(PATHDOC) ]];
+          then
+            echo "Not found generated doc at path $(PATHDOC)"
+            exit 1
+          fi
+        displayName: Build doc
+
+      - task: AzureCLI@2
+        inputs:
+          azureSubscription: $(serviceConnectionSandbox)
+          scriptType: bash
+          scriptLocation: inlineScript
+          inlineScript: |
+            if [[ -d backstage ]]; then cd backstage ; fi
+            aip core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
+        displayName: Push doc
 
 
   - job: DeploySandbox
@@ -145,16 +147,16 @@ jobs:
 
 
   - job: BuildForSdxDev
-#    dependsOn: TestAndBuild
-#    condition: and(
-#        succeeded(),
-#        or(
-#            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
-#            eq(variables['deploy_sdxdev'], 'true')
-#        )
-#      )
+    dependsOn: TestAndBuild
+    condition: and(
+        succeeded(),
+        or(
+            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
+            eq(variables['deploy_sdxdev'], 'true')
+        )
+      )
     pool:
-      vmImage: ubuntu-latest
+      vmImage: ubuntu-24.04
     container:
       image: aziecr1aip001.azurecr.io/aip_devcontainer
       endpoint: SDXSandbox_Docker_Registry
@@ -167,10 +169,6 @@ jobs:
 
       - bash: |
           set -e
-          docker stop $(docker ps -q)
-          docker rm $(docker ps -aq)
-          docker rmi -f $(docker images -aq)
-          docker system prune -a --volumes -f
           echo "Build backstage backend..."
           aip -i SDXDEV app container build --container_name backstage_app_back
           echo "Build backstage frontend..."
@@ -195,13 +193,13 @@ jobs:
 
   - job: DeploySdxDev
     dependsOn: BuildForSdxDev
-#    condition: and(
-#        succeeded(),
-#        or(
-#            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
-#            eq(variables['deploy_sdxdev'], 'true')
-#        )
-#      )
+    condition: and(
+        succeeded(),
+        or(
+            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
+            eq(variables['deploy_sdxdev'], 'true')
+        )
+      )
     pool:
       name: DevOps agent pool NON-PROD CICD - SDP
     container:
