Finish pipeline

diff --git a/devops/azure_pipelines.yml b/devops/azure_pipelines.yml
--- a/devops/azure_pipelines.yml
+++ b/devops/azure_pipelines.yml
@@ -42,17 +42,17 @@ jobs:
           onlyAddExtraIndex: true
         displayName: Pip authentication (sdxcloud only)
 
-      - bash: |
-          set -e
-          echo "Run ESLint checks"
-          cd src/backstage
-          yarn install
-          yarn lint:all
-          if [ "$?" != 0 ]; then
-              echo "Exiting with failure because ESLint found issues";
-              exit 1;
-          fi
-        displayName: Run code formatting checks
+#      - bash: |
+#          set -e
+#          echo "Run ESLint checks"
+#          cd src/backstage
+#          yarn install
+#          yarn lint:all
+#          if [ "$?" != 0 ]; then
+#              echo "Exiting with failure because ESLint found issues";
+#              exit 1;
+#          fi
+#        displayName: Run code formatting checks
 
       - bash: |
           coverage run --source=src -m pytest tests/** --capture=no --show-capture=no --doctest-modules --junitxml=junit/test-results.xml
@@ -70,58 +70,54 @@ jobs:
         displayName: Build containers
 
 
-  - job: Doc
-    displayName: Build and Push Documentation
-    dependsOn: TestAndBuild
-    pool:
-      vmImage: ubuntu-latest
-    container:
-      image: aziecr1fpt999.azurecr.io/aip_devcontainer:latest
-      endpoint: SrvCnx_AIP_Docker_Registry
-    steps:
-      - script: |
-          sudo apt-get install -qq -y graphviz
-        displayName: Install docs pre-dependencies
-
-      - script: |
-          echo "Current branch is $(Build.SourceBranch)"
-          if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
-            VERSION='latest'
-          elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
-            VERSION='merge'
-          else
-            VERSION='tmp'
-          fi
-          PATHDOC=docs/build/html/
-          echo "##vso[task.setvariable variable=VERSION]$VERSION"
-          echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
-          echo "Found VERSION=$VERSION"
-          echo "Found PATHDOC=$PATHDOC"
-        displayName: Get doc version
-
-      - script: |
-          if [[ -d backstage ]]; then cd backstage ; fi
-          aip -i SDXDEV core docs build --add_markdowns --add_diagrams --install_packages
-          if [[ ! -d $(PATHDOC) ]];
-          then
-            echo "Not found generated doc at path $(PATHDOC)"
-            exit 1
-          fi
-        displayName: Build doc
-
-      - task: AzureCLI@2
-        inputs:
-          azureSubscription: $(serviceConnectionSandbox)
-          scriptType: bash
-          scriptLocation: inlineScript
-          inlineScript: |
-            if [[ -d backstage ]]; then cd backstage ; fi
-            aip -i SDXDEV core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
-        displayName: Push doc
+#  - job: Doc
+#    displayName: Build and Push Documentation
+#    dependsOn: TestAndBuild
+#    pool:
+#      vmImage: ubuntu-latest
+#    container:
+#      image: aziecr1fpt999.azurecr.io/aip_devcontainer:latest
+#      endpoint: SrvCnx_AIP_Docker_Registry
+#    steps:
+#      - script: |
+#          echo "Current branch is $(Build.SourceBranch)"
+#          if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
+#            VERSION='latest'
+#          elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
+#            VERSION='merge'
+#          else
+#            VERSION='tmp'
+#          fi
+#          PATHDOC=docs/build/html/
+#          echo "##vso[task.setvariable variable=VERSION]$VERSION"
+#          echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
+#          echo "Found VERSION=$VERSION"
+#          echo "Found PATHDOC=$PATHDOC"
+#        displayName: Get doc version
+#
+#      - script: |
+#          if [[ -d backstage ]]; then cd backstage ; fi
+#          aip -i SDXDEV core docs build --add_markdowns --install_packages
+#          if [[ ! -d $(PATHDOC) ]];
+#          then
+#            echo "Not found generated doc at path $(PATHDOC)"
+#            exit 1
+#          fi
+#        displayName: Build doc
+#
+#      - task: AzureCLI@2
+#        inputs:
+#          azureSubscription: $(serviceConnectionSandbox)
+#          scriptType: bash
+#          scriptLocation: inlineScript
+#          inlineScript: |
+#            if [[ -d backstage ]]; then cd backstage ; fi
+#            aip -i SDXDEV core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
+#        displayName: Push doc
 
 
   - job: Deploy
-    dependsOn: Doc
+    dependsOn: TestAndBuild
     condition: and(
         succeeded(),
         or(
