comm doc

diff --git a/devops/azure_pipelines.yml b/devops/azure_pipelines.yml
--- a/devops/azure_pipelines.yml
+++ b/devops/azure_pipelines.yml
@@ -58,58 +58,58 @@ jobs:
         displayName: Run ESLint checks
 
 
-  - job: Doc
-    displayName: Build and Push Documentation
-    dependsOn: TestAndBuild
-    pool:
-      vmImage: ubuntu-latest
-    container:
-      image: aziecr1aip001.azurecr.io/aip_devcontainer
-      endpoint: SDXSandbox_Docker_Registry
-    steps:
-      - task: PipAuthenticate@1
-        inputs:
-          artifactFeeds: $(artifactFeeds)
-          onlyAddExtraIndex: true
-        displayName: Pip authentication
+  # - job: Doc
+  #   displayName: Build and Push Documentation
+  #   dependsOn: TestAndBuild
+  #   pool:
+  #     vmImage: ubuntu-latest
+  #   container:
+  #     image: aziecr1aip001.azurecr.io/aip_devcontainer
+  #     endpoint: SDXSandbox_Docker_Registry
+  #   steps:
+  #     - task: PipAuthenticate@1
+  #       inputs:
+  #         artifactFeeds: $(artifactFeeds)
+  #         onlyAddExtraIndex: true
+  #       displayName: Pip authentication
 
-      - script: |
-          echo "Current branch is $(Build.SourceBranch)"
-          if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
-            VERSION='latest'
-          elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
-            VERSION='merge'
-          else
-            VERSION='tmp'
-          fi
-          PATHDOC=docs/build/html/
-          echo "##vso[task.setvariable variable=VERSION]$VERSION"
-          echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
-          echo "Found VERSION=$VERSION"
-          echo "Found PATHDOC=$PATHDOC"
-        displayName: Get doc version
+  #     - script: |
+  #         echo "Current branch is $(Build.SourceBranch)"
+  #         if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
+  #           VERSION='latest'
+  #         elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
+  #           VERSION='merge'
+  #         else
+  #           VERSION='tmp'
+  #         fi
+  #         PATHDOC=docs/build/html/
+  #         echo "##vso[task.setvariable variable=VERSION]$VERSION"
+  #         echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
+  #         echo "Found VERSION=$VERSION"
+  #         echo "Found PATHDOC=$PATHDOC"
+  #       displayName: Get doc version
 
-      - script: |
-          set -e
-          export PATH="$HOME/.local/bin:$PATH"
-          if [[ -d backstage ]]; then cd backstage ; fi
-          aip core docs build --add_markdowns --install_packages
-          if [[ ! -d $(PATHDOC) ]];
-          then
-            echo "Not found generated doc at path $(PATHDOC)"
-            exit 1
-          fi
-        displayName: Build doc
+  #     - script: |
+  #         set -e
+  #         export PATH="$HOME/.local/bin:$PATH"
+  #         if [[ -d backstage ]]; then cd backstage ; fi
+  #         aip core docs build --add_markdowns --install_packages
+  #         if [[ ! -d $(PATHDOC) ]];
+  #         then
+  #           echo "Not found generated doc at path $(PATHDOC)"
+  #           exit 1
+  #         fi
+  #       displayName: Build doc
 
-      - task: AzureCLI@2
-        inputs:
-          azureSubscription: $(serviceConnectionSandbox)
-          scriptType: bash
-          scriptLocation: inlineScript
-          inlineScript: |
-            if [[ -d backstage ]]; then cd backstage ; fi
-            aip core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
-        displayName: Push doc
+  #     - task: AzureCLI@2
+  #       inputs:
+  #         azureSubscription: $(serviceConnectionSandbox)
+  #         scriptType: bash
+  #         scriptLocation: inlineScript
+  #         inlineScript: |
+  #           if [[ -d backstage ]]; then cd backstage ; fi
+  #           aip core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
+  #       displayName: Push doc
 
 
   - job: DeploySandbox
